Stock tracker/config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  delete 'user_stocks', to: 'user_stocks#destroy'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  delete 'my_friends', to: 'users#destroy_friends'
  post 'my_friends', to: 'users#add_friends'
  post 'friend_stocks', to: 'users#view_stocks'
end

Stock tracker/app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

Stock tracker/app/models/stock.rb
class Stock < ApplicationRecord
  # include HTTParty
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, presence: true


  def self.new_lookup(ticker_symbol)
    # response = get("/stocks/#{stock_name}/price")
    # if response.success?
    #   return response['price']
    # else
    #   return nil
    # end
    if (ticker_symbol == nil || ticker_symbol == '' || has_digits(ticker_symbol) || ticker_symbol.length != 3 || !(ticker_symbol == ticker_symbol.upcase) )
      return nil
    else
      if (Stock.find_by(ticker: ticker_symbol).present?)
        return Stock.find_by(ticker: ticker_symbol)
      else
        stock = Stock.create(ticker: ticker_symbol, name: ticker_symbol + ' Company', last_price: rand(101.2...504.9).round(3) )
        stock.save
        return stock
      end
    end
  end

  def self.has_digits(str)
    str.count("0-9") > 0
  end

  def view
    
  end
end

Stock tracker/app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Stock tracker/app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

Stock tracker/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end

end

Stock tracker/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      @tracked_stocks = current_user.stocks
      if @stock
        render 'users/my_portfolio'
      else
        flash[:alert] = 'Please enter a valid sympol to search'
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = 'Please enter a sympol to search'
      redirect_to my_portfolio_path
    end
  end
end

Stock tracker/app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def index
    if (Stock.find_by(ticker: params[:ticker]).present?)
      stock = Stock.find_by(ticker: params[:ticker])
    else
      stock = Stock.create(ticker: params[:ticker], name: (params[:name].to_s + ' Company'), last_price: params[:last_price])
    end
    if (!current_user.stocks.include?(stock))
      current_user.stocks << stock
    else
      flash[:alert] = 'Stock already tracked'
    end
    redirect_to my_portfolio_path
  end


  def destroy
    stock = Stock.find_by(ticker: params[:ticker])
    if (current_user.stocks.include?(stock))
      current_user.stocks.delete(stock)
      flash[:alert] = 'Stock already deleted'
    end
    redirect_to my_portfolio_path
  end
end

Stock tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end
  def my_friends
    @friends = current_user.friends
  end

  def search
    # render json: params[:friend]
    @friends = current_user.friends
    if User.where(email: params[:friend].to_s).present?
      searchingFriend = User.where(email: params[:friend].to_s)
        @friend = ((searchingFriend.first.present?)? (searchingFriend.first) : {})
        render 'users/my_friends'
      # redirect_to 'users/my_friends'
    else
      flash[:alert] = 'Email not found'
      redirect_to my_friends_path
    end
  end

  def destroy_friends
    if params[:friend_id].present?
      destroyUser = User.find_by(id: params[:friend_id])
      current_user.friends.destroy(destroyUser)
      redirect_to my_friends_path
    end
  end
  def add_friends
    if params[:friend_id].present?
      addUser = User.find_by(id: params[:friend_id])
      if current_user != addUser
        current_user.friends << addUser
      else
        flash[:alert] = 'You cannot follow yourself'
      end
      redirect_to my_friends_path
    end
  end
  def view_stocks
    user = User.find_by(id: params[:friend_id])
    @tracked_stocks = user.stocks
  end
end

Stock tracker/app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

Stock tracker/app/helpers/users_helper.rb
module UsersHelper
end

Stock tracker/app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><%= friend.email %></td>
            <td class= " float-right row m-0 w-100 ">
              <%= button_to 'Stop following',
                my_friends_path(friend_id: friend.id),
                method: :delete,
                data: {confirm: 'Are you sure?'},
                class: 'btn btn-sm btn-warning btn-block '%>

                <%= button_to 'View stocks',
                friend_stocks_path(friend_id: friend.id),
                method: :post,
                class: 'btn btn-sm btn-primary btn-block'%>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

Stock tracker/app/views/users/my_friends.html.erb
<div class='search-area m-4 p-4'>
    <h3>Search friends </h3>
    <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          Search
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @friend %>
    <div class='card card-header d-inline-block mb-3'>
        <strong>Email: </strong> <%= @friend.email%>
        <% if (!current_user.friends.include?(@friend) ) %>
        <%= button_to 'Follow',
            my_friends_path(friend_id: @friend.id),
            class: "btn btn-sm btn-success", method: :post %>
        <% elsif current_user.email.to_s == @friend.email.to_s %>
          <%= link_to 'You cannot follow yourself', '#', class: "btn btn-sm btn-danger disabled " %>
        <% else %>
         <%= link_to 'Followed', '#', class: "btn btn-sm btn-danger disabled " %>
        <% end %>
    </div>
  <% end %>

  <% if !@friends.empty? %>
    <%= render 'friends/list' %>
  <% end %>

</div>

Stock tracker/app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>


<div class='search-area m-4 p-4'>
    <h3>Search stock </h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          Search
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @stock %>
    <div class='card card-header d-inline-block mb-3'>
        <strong>Symbol: </strong> <%= @stock.ticker%>
        <strong>Name: </strong> <%= @stock.name%>
        <strong>Price: </strong> <%= @stock.last_price%>
        <% if (!current_user.stocks.include?(@stock)) %>
        <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker, last_price: @stock.last_price ),
                                    class: "btn btn-sm btn-success", method: :post %>
        <% else %>
         <%= link_to 'Tracked', class: "btn btn-sm btn-danger " %>
        <% end %>
    </div>
  <% end %>
  <% if @tracked_stocks != nil%>
    <%= render 'stocks/list'%>
  <% end %>
</div>

Stock tracker/app/views/users/view_stocks.erb
<h1>Portfolio of user<%=  %></h1>


<div class='search-area m-4 p-4'>
    <h3>Search stock </h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          Search
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @stock %>
    <div class='card card-header d-inline-block mb-3'>
        <strong>Symbol: </strong> <%= @stock.ticker%>
        <strong>Name: </strong> <%= @stock.name%>
        <strong>Price: </strong> <%= @stock.last_price%>
        <% if (!current_user.stocks.include?(@stock)) %>
        <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker, last_price: @stock.last_price ),
                                    class: "btn btn-sm btn-success", method: :post %>
        <% else %>
         <%= link_to 'Tracked', class: "btn btn-sm btn-danger " %>
        <% end %>
    </div>
  <% end %>
  <% if @tracked_stocks != nil%>
    <div class="row">
        <div class="col-9">
            <table class="table table-bordered table-hover">
            <thead>
                <tr>
                <th scope="col">Ticker</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @tracked_stocks.each do |stock| %>
                <tr>
                    <th scope="row"><%= stock.ticker %></th>
                    <td><%= stock.name %></td>
                    <td><%= stock.last_price %>$</td>
                    <td>
                        <% if (!current_user.stocks.include?(stock)) %>
                        <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker, last_price: stock.last_price ),
                                                    class: "btn btn-sm btn-success", method: :post %>
                        <% else %>
                        <%= link_to 'Tracked', '#', class: "btn btn-sm btn-danger disable" %>
                        <% end %>
                    </td>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
        </div>

  <% end %>
</div>